# ats_tracker/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),  # Root URL shows login page
    path('home/', views.home, name='home'),    # Home page after login
    path('teams/add-member/', views.add_member, name='add_member'),
    path('create-team/', views.create_team, name='create_team'),
    path('team-members/<int:team_id>/', views.team_members, name='team_members'),
    path('teams/', views.view_edit_teams, name='view_edit_teams'),
    path('teams/<int:team_id>/members/', views.team_members_api, name='team_members_api'),
    path('teams/<int:team_id>/add_member/', views.add_member_api, name='add_member_api'),
    path('teams/<int:team_id>/remove_member/', views.remove_member_api, name='remove_member_api'),
    path('jds/', views.create_jd_view, name='jd_create'),
    path('jds/create/', views.create_jd, name='create_jd'),
    path('jds/<str:jd_id>/', views.jd_detail, name='jd_detail'),
    path('create_customer/', views.create_customer, name='create_customer'),
    path('update_customer/<int:company_id>/', views.update_customer, name='update_customer'),
    path('delete_customer/<int:company_id>/', views.delete_customer, name='delete_customer'),
    path('customer_details/', views.customer_details, name='customer_details'),
    path('view_edit_jds/', views.view_edit_jds, name='view_edit_jds'),
    path('get_jd/<str:jd_id>/', views.get_jd, name='get_jd'),
    path('update_jd/<str:jd_id>/', views.update_jd, name='update_jd'),
    path('assign_jd/', views.assign_jd, name='assign_jd'),
    path('assign_jd_data/', views.assign_jd_data, name='assign_jd_data'),
    path('assign_jd_page/', views.assign_jd_page, name='assign_jd_page'),
    path('employee_view/', views.employee_view_page, name='employee_view_page'),
    path('employee_view_data/', views.employee_view_data, name='employee_view_data'),
    path('employee_view_report/', views.employee_view_report, name='employee_view_report'),
    path('upload_resume/', views.upload_resume_page, name='upload_resume_page'),
    path('api/upload_resume/', views.upload_resume, name='api_upload_resume'),
    path('api/recent_resumes/', views.recent_resumes, name='api_recent_resumes'),
    path('download_resume/<int:resume_id>/', views.download_resume, name='download_resume'),
    path('view_parse_resumes_page/', views.view_parse_resumes_page, name='view_parse_resumes_page'),
    path('view_parse_resumes/', views.view_parse_resumes, name='view_parse_resumes'),
    path('update_resume_status/', views.update_resume_status, name='update_resume_status'),
    path('download_resume/<int:resume_id>/', views.download_resume, name='download_resume'),
    path('assign_jd_data/', views.assign_jd_data, name='assign_jd_data'),
    # urls.py
    path('get_candidate_details/', views.get_candidate_details, name='get_candidate_details'),
    path('export_resumes_excel/', views.export_resumes_excel, name='export_resumes_excel'),
    path('parse_resumes/', views.parse_resumes, name='parse_resumes'),
    path('save_candidate_details/', views.save_candidate_details, name='save_candidate_details'),
    path('update_candidate_screen_status/', views.update_candidate_screen_status, name='update_candidate_screen_status'),
    path('get_jd_team_members/', views.get_jd_team_members, name='get_jd_team_members'),
    # urls.py
    path('schedule_interviews/', views.schedule_interviews_page, name='schedule_interviews_page'),
    path('get_candidates_for_jd/', views.get_candidates_for_jd, name='get_candidates_for_jd'),
    path('schedule_interview/', views.schedule_interview, name='schedule_interview'),
    path('record_interview_result/', views.record_interview_result_page, name='record_interview_result_page'),
    path('submit_interview_result/', views.submit_interview_result, name='submit_interview_result'),
    path('manage_candidate_status/', views.manage_candidate_status_page, name='manage_candidate_status'),
    path('manage_candidate_status_data/', views.manage_candidate_status_data, name='manage_candidate_status_data'),
    path('update_candidate_status/', views.update_candidate_status, name='update_candidate_status'),
    path('view_finalized_candidates/', views.view_finalized_candidates, name='view_finalized_candidates'),
    path('api/jds/', views.api_jds, name='api_jds'),
    path('api/finalized_candidates/', views.api_finalized_candidates, name='api_finalized_candidates'),
    path('api/candidate_details/', views.api_candidate_details, name='api_candidate_details'),
    path('logout/', views.logout_page, name='logout'),
    path('candidate-profile/', views.candidate_profile, name='candidate_profile'),
    path('get_candidate_details_profile/', views.get_candidate_details_profile, name='get_candidate_details_profile'),
    path('save_candidate_details_profile/', views.save_candidate_details_profile, name='save_candidate_details_profile'),
    path('candidate_suggestions/', views.candidate_suggestions, name='candidate_suggestions'),

    path('dashboard_data/', views.dashboard_data, name='dashboard_data'),
    path('offer_letter/', views.offer_letter_page, name='offer_letter'),
    path('api/generate_offer/', views.generate_offer_letter, name='generate_offer_letter'),
    path('team_reports/', views.team_reports_page, name='team_reports'),
    path('api/team_report_filters/', views.team_report_filters, name='team_report_filters'),
    path('api/team_reports/', views.team_reports_api, name='team_reports_api'),
    path('api/team_reports/export/', views.team_reports_export, name='team_reports_export'),

    path('task_progress_reports/', views.task_progress_reports_page, name='task_progress_reports'),
    path('api/team_report_filters/', views.team_report_filters, name='team_report_filters'),
    path('api/team_reports/', views.team_reports_api, name='team_reports_api'),
    path('api/team_reports/export/', views.team_reports_export, name='team_reports_export'),
    path('api/jds/<str:jd_id>/', views.api_jd_detail, name='api_jd_detail'),
    path('candidate_conversion_rates/', views.candidate_conversion_rates_page, name='candidate_conversion_rates'),
    path('api/ccr_filters/', views.ccr_filters, name='ccr_filters'),
    path('api/ccr_reports/', views.ccr_reports_api, name='ccr_reports_api'),
    path('api/ccr_reports/export/', views.ccr_reports_export, name='ccr_reports_export'),
    # ... other urls

    # settings urls
    path('user/', views.user_profile, name='user_profile'),

    path('manage_sessions/', views.manage_sessions_view, name='manage_sessions'),
    path('manage_sessions/logout_session/', views.logout_session_api, name='logout_session_api'),
    path('access_permissions/', views.access_permissions, name='access_permissions'),
    path('access_permissions/change_password/', views.change_password, name='change_password'),
    path('access_permissions/change_role/', views.change_role, name='change_role'),
    path('status_report/', views.status_report_page, name='status_report'),
    path('status_report/generate/', views.generate_status_report, name='generate_status_report'),
    path("teams/export/", views.export_teams_excel, name="export_teams_excel"),
    path('api/teams/list/', views.teams_list),
    path('api/teams/filters/', views.teams_filters),
    path('api/teams/report/', views.team_report),
    path('export_team_reports_excel/', views.export_team_reports_excel),
    path("settings/notification/", views.notification_settings, name="notification_settings"),
    path("settings/notification/toggle/", views.toggle_notification, name="toggle_notification"),

    path("settings/notification/", views.notification_settings, name="notification_settings"),
    path("settings/notification/toggle/", views.toggle_notification, name="toggle_notification"),
    path("settings/notification/clear_all/", views.clear_all_notifications, name="clear_all_notifications"),
    path("settings/notification/count/", views.notification_count, name="notification_count"),
    path("settings/notification/mark_read/<int:notification_id>/", views.mark_as_read_notification, name="mark_notification_read"),

    # email config paths
    # path("settings/email/", views.settings_email_config, name="settings_email_config"),
    path("settings/email/", views.save_email_config, name="save_email_config"),

]